<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>mhml</string>
            <string>mtpl</string>
            <string>mh.xml</string>
            <string>mh.html</string>
            <string>mh.htm</string>
            <string>mh.tpl</string>
        </array>
        <key>name</key>
        <string>Mahalo Markup Language</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>(&lt;/?)([a-z][a-zA-Z0-9:-]*)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.begin.mhml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag.other.mhml</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>&gt;</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.end.mhml</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.start-tag.other.html</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#tag-stuff</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>begin</key>
                <string>(\$|\?)(\{)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.mhml</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.output.mhml</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>\}</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.output.mhml</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.expression.output.mhml</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#expression-output</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>include</key>
                <string>text.html.basic</string>
            </dict>
        </array>
        <key>repository</key>
	    <dict>
            <key>expression-output</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>begin</key>
                        <string>\{</string>
                        <key>end</key>
                        <string>\}</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#expression-output</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string-single-quoted</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#expression-stuff</string>
                    </dict>
                </array>
            </dict>
            <key>expression-stuff</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\.|:|,|\+|\-|\*|/|%|\?|!=|!|==|&lt;=|&gt;=|&lt;|&gt;|\|\||\||&amp;&amp;|\(|\)|\[|\]|\{|\}</string>
                        <key>name</key>
                        <string>keyword.operator.mhml</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b(true|false|null)\b</string>
                        <key>name</key>
                        <string>constant.language.mhml</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\b[0-9]+(\.[0-9]+)?\b</string>
                        <key>name</key>
                        <string>constant.numeric.mhml</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\$?\b([\w]+)\b</string>
                        <key>name</key>
                        <string>meta.object.member.mhml</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#string-double-quoted</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>[^\s]</string>
                        <key>name</key>
                        <string>invalid.illegal</string>
                    </dict>
                </array>
            </dict>
            <key>string-double-quoted</key>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"</string>
                <key>name</key>
                <string>string.quoted.double.mhml</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string-character-escape</string>
                    </dict>
                </array>
            </dict>
            <key>string-single-quoted</key>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>end</key>
                <string>'</string>
                <key>name</key>
                <string>string.quoted.single.mhml</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string-character-escape</string>
                    </dict>
                </array>
            </dict>
            <key>string-character-escape</key>
            <dict>
                <key>match</key>
                <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)</string>
                <key>name</key>
                <string>constant.character.escape</string>
            </dict>
            <key>tag-stuff</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>(?&lt;=[^=])\b([a-zA-Z0-9-]+)</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.control.mhml</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>entity.other.attribute-name.mhml</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>@|\$|\?(?=[a-zA-Z0-9-]+)</string>
                        <key>name</key>
                        <string>keyword.operator.mhml</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>(=)(')</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>keyword.control.mhml</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.attribute.mhml</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>'</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.tag.attribute.mhml</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>meta.expression.attribute.mhml</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#expression-stuff</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>"</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.begin.mhml</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>"</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.string.end.mhml</string>
                            </dict>
                        </dict>
                        <key>name</key>
                        <string>string.quoted.double.mhml</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(?&lt;==)(?:[^\s&lt;&gt;/'"]|/(?!&gt;))+</string>
                        <key>name</key>
                        <string>string.unquoted.html</string>
				    </dict>
                    <dict>
                        <key>match</key>
                        <string>[^\s]</string>
                        <key>name</key>
                        <string>punctuation.definition.tag.inside.mhml</string>
                    </dict>
                </array>
            </dict>
        </dict>
        <key>scopeName</key>
        <string>text.html.mhml</string>
    </dict>
</plist>